app/urls.py
from django.urls import re_path, path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'^$', views.Events.as_view(), name='event_list'),
    re_path(r'^event/(?P<e_id>[0-9]+)/$', views.EventDetail.as_view(), name='detail'),
    re_path(r'^event/(?P<e_id>[0-9]+)/register/$', views.EventRegister.as_view(), name='register'),
    re_path(r'^contact/$', views.Contact.as_view(), name='contact'),
    re_path(r'^ajax_calls/search/', views.autocompleteModel),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

registration/registertion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
# from phonenumber_field.modelfields import PhoneNumberField


class Event(models.Model):
    name = models.CharField(max_length=100, null=False, blank=True)
    description = models.CharField(max_length=1000, null=False, blank=True)
    avatar = models.ImageField(upload_to='event_pic', null=True, blank=True)
    video = models.FileField(upload_to='event_video', null=True, blank=True)
    venue = models.CharField(max_length=100, null=False, blank=True)
    timestamp = models.DateTimeField(default=None, null=True)
    seats = models.IntegerField(null=False, blank=True)

    def __str__(self):
        return str(self.id)


class Register(models.Model):

    STATE_CHOICE = (
        ('Andhra Pradesh', 'Andhra Pradesh'),
        ('Arunachal Pradesh','Arunachal Pradesh'),
        ('Assam', 'Assam'),
        ('Bihar', 'Bihar'),
        ('Chhattisgarh', 'Chhattisgarh'),
        ('Goa', 'Goa'),
        ('Gujarat', 'Gujarat'),
        ('Haryana', 'Haryana'),
        ('Himachal Pradesh', 'Himachal Pradesh'),
        ('Jammu and Kashmir', 'Jammu and Kashmir'),
        ('Jharkhand', 'Jharkhand'),
        ('Karnataka', 'Karnataka'),
        ('Kerala', 'Kerala'),
        ('Madhya Pradesh','Madhya Pradesh'),
        ('Maharashtra', 'Maharashtra'),
        ('Manipur', 'Manipur'),
        ('Meghalaya', 'Meghalaya'),
        ('Mizoram', 'Mizoram'),
        ('Nagaland', 'Nagaland'),
        ('Orissa', 'Orissa'),
        ('Punjab', 'Punjab'),
        ('Rajasthan', 'Rajasthan'),
        ('Sikkim', 'Sikkim'),
        ('Tamil Nadu', 'Tamil Nadu'),
        ('Telagana', 'Telagana'),
        ('Tripura', 'Tripura'),
        ('Uttaranchal', 'Uttaranchal'),
        ('Uttar Pradesh', 'Uttar Pradesh'),
        ('West Bengal', 'West Bengal'),
        ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'),
        ('Chandigarh', 'Chandigarh'),
        ('Dadar and Nagar Haveli', 'Dadar and Nagar Haveli'),
        ('Daman and Diu', 'Daman and Diu'),
        ('Delhi', 'Delhi'),
        ('Lakshadeep', 'Lakshadeep'),
        ('Pondicherry', 'Pondicherry')
    )

    CATEGORY_CHOICE = (
        ('Govt', 'Govt'),
        ('Private', 'Private')
    )

    GENDER_CHOICE = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other')
    )

    first_name = models.CharField(max_length=50, null=False, blank=False)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=False, blank=False)
    gender = models.CharField(max_length=50, blank=False, null=False, choices=GENDER_CHOICE)
    email = models.EmailField(null=False, blank=False)
    address = models.CharField(null=False, blank=False, max_length=200)
    city = models.CharField(null=False, blank=False, max_length=50)
    state = models.CharField(max_length=50, blank=True,null=True, choices=STATE_CHOICE)
    pincode = models.IntegerField(blank=False, null=False)
    category = models.CharField(max_length=50, blank=True, null=True, choices=CATEGORY_CHOICE)
    organisation = models.CharField(max_length=50, null=False, blank=False)
    designation = models.CharField(max_length=50, null=False, blank=False)
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    event_name = models.CharField(max_length=100, null=False, blank=True)
    # captcha = models.IntegerField(blank=False, null=False)

    def __str__(self):
        return str(self.id)


class Contact(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    enquiry = models.CharField(max_length=500, blank=False, null=False)

    def __str__(self):
        return str(self.id)

app/forms.py
from django import forms
from .models import *


class RegisterForm(forms.ModelForm):

    captcha = forms.IntegerField(required=True)

    class Meta:
        model = Register
        fields = ('captcha', 'first_name', 'middle_name', 'last_name', 'gender', 'email', 'address', 'city', 'state',
                  'pincode', 'category', 'organisation', 'designation')


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('name', 'email', 'enquiry')

app/templates/app/event_register.html
{% extends 'app/base.html' %}
{% load staticfiles %}
{% block register %}
<!DOCTYPE html>
<html xmlns:margin-left="http://www.w3.org/1999/xhtml">
<head>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

</head>
<body>
<form method="post" style="margin-left:1vw; font-size:1.5vw;">

    {% csrf_token %}
                <h4>PERSONAL DETAILS</h4>

     <span style="font-size:1.2vw;margin-left:10vw;">First Name </span><span style="color:red;">*</span>
     <span style="font-size:1vw; margin-left:0.6vw;"> {{ form.first_name }}</span>
     <span id="first_name_err" class='validationerror' style="font-size:1vw; margin-right:-8.48vw; color:red;"></span>


     <span style="font-size:1.2vw; margin-left:10vw;">Middle Name </span>
     <span style="font-size:1vw; margin-left:1vw;"> {{ form.middle_name }}</span>
     <span id="middle_name_err" class='validationerror' style="font-size:1vw; color:red;"></span>


        <br><br>

     <span style="font-size:1.2vw; margin-left:10vw;">Last Name</span><span style="color:red;">*</span>
     <span style="font-size:1vw; margin-left:1vw;">{{ form.last_name }}</span>
     <span id="last_name_err" class='validationerror' style="font-size:1vw; margin-right:-8.48vw; color:red;"></span>


     <span style="font-size:1.2vw;margin-left:10vw;">Gender</span><span style="color:red;">*</span>
     <span style="font-size:1vw; margin-left:4vw; "> {{ form.gender }}</span>

        <br><br>

     <span style="font-size:1.2vw; margin-left:10vw;">Address</span><span style="color:red;">*</span>
     <span style="font-size:1vw; margin-left:2.5vw;">{{ form.address }}</span>
     <span id="address_err" class='validationerror' style="font-size:1vw; margin-right:-7.8vw; color:red;"></span>


     <span style="font-size:1.2vw; margin-left:10vw;">City</span><span style="color:red;">*</span>
     <span style="font-size:1vw; margin-left:6vw;">{{ form.city }}</span>
     <span id="city_err" class='validationerror' style="font-size:1vw; color:red;"></span>

        <br><br>

     <span style="font-size:1.2vw; margin-left:10vw;">State</span><span style="color:red;">*</span>
     <span style="font-size:1vw; margin-left:4vw;">{{ form.state }}</span>


     <span style="font-size:1.2vw; margin-left:8.9vw;">Pincode</span><span style="color:red;">*</span>
     <span style="font-size:1vw; margin-left:3.6vw;">{{ form.pincode }}</span>
     <span id="pincode_err" class='validationerror' style="font-size:1vw; color:red;"></span>

        <br><br>

     <span style="font-size:1.2vw; margin-left:10vw;">Email</span><span style="color:red;">*</span>
     <span style="font-size:1vw; margin-left:3.9vw;">{{ form.email }}</span>
     <span id="email_err" class='validationerror' style="font-size:1vw; color:red;"></span>

        <br><br>

        <h4>ORGANISATION DETAILS</h4>

        <span style="font-size:1.2vw; margin-left:10vw;">Category</span><span style="color:red;">*</span>
        <span style="font-size:1vw; margin-left:2.2vw;">{{ form.category }}</span>


        <span style="font-size:1.2vw; margin-left:19vw;">Organisation</span><span style="color:red;">*</span>
        <span style="font-size:1vw; margin-left:1vw;">{{ form.organisation }}</span>
        <span id="org_err" class='validationerror' style="font-size:1vw; color:red;"></span>

        <br><br>

        <span style="font-size:1.2vw; margin-left:10vw;">Designation</span><span style="color:red;">*</span>
        <span style="font-size:1vw; margin-left:0.7vw;">{{ form.designation }}</span>
        <span id="des_err" class='validationerror' style="font-size:1vw; margin-right:-8.8vw; color:red;"></span>


        <span style="font-size:1.2vw; margin-left:10vw;">Captcha</span><span style="color:red;">*</span>
        <span id="sum" style="font-size:1.2vw;">{{a}}+{{b}}=</span>
        <span style="font-size:1vw; margin-left:0.2vw;">{{ form.captcha }}</span>
        <span id="captcha_err" class='validationerror' style="font-size:1vw; color:red;"></span>

        <br><br>

    <button id="id_submit" class="w3-button w3-black w3-round-xxlarge" style="text-decoration:none; font-size:1.2vw; color:white; margin-left:10vw;" >Register</button>
</form>
{% for message in messages %}
<p style="color:red; margin-left:40vw; margin-top:-0.5vw; font-size:1.5vw;">{{ message }}</p>
{% endfor %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script>
var submit = false;
$(document).ready(function () {
        $(".validationerror").hide();

        $("#id_first_name").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[a-zA-Z ]{2,30}$");
                if (!regex.test($(this).val())) {
                    document.getElementById('first_name_err').innerHTML = "Invalid First Name";
                    $("#first_name_err" ).show();
                    submit = false;
                }
            }
        });

        $("#id_first_name").focusin(function (event) {
            if (event.charCode!=0) {
                $( "#first_name_err" ).hide();
                document.getElementById('first_name_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_middle_name").focusout(function (event) {
            if (event.charCode!=0 || event.charCode==0) {
                var regex = new RegExp("^[a-zA-Z ]{2,30}$");
                if (!regex.test($(this).val())) {
                    document.getElementById('middle_name_err').innerHTML = "Invalid Middle Name";
                    $("#middle_name_err" ).show();
                    submit = false;
                }
            }
        });

        $("#id_middle_name").focusin(function (event) {
            if (event.charCode!=0 || event.charCode==0) {
                $( "#middle_name_err" ).hide();
                document.getElementById('middle_name_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_last_name").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[a-zA-Z ]{2,30}$");
                if (!regex.test($(this).val())) {
                    document.getElementById('last_name_err').innerHTML = "Invalid Last Name";
                    $("#last_name_err" ).show();
                    submit = false;
                }
            }
        });

        $("#id_last_name").focusin(function (event) {
            if (event.charCode!=0) {
                $("#last_name_err" ).hide();
                document.getElementById('last_name_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_address").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[a-zA-Z0-9.- ]{2,50}$");
                if (!regex.test($(this).val())) {
                    document.getElementById('address_err').innerHTML = "Invalid Adddress";
                    $("#address_err" ).show();
                    submit = false;
                }
            }
        });

        $("#id_address").focusin(function (event) {
            if (event.charCode!=0) {
                $("#address_err" ).hide()
                document.getElementById('address_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_email").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[+a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$");
                if (!regex.test($("#id_email").val())) {
                    document.getElementById('email_err').innerHTML = "Invalid Email Id";
                    $( "#email_err" ).show();
                    submit = false;
                }
            }
        });

        $("#id_email").focusin(function (event) {
            if (event.charCode!=0) {
                $( "#email_err" ).hide();
                document.getElementById('email_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_city").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[a-zA-Z ]+$");
                if (!regex.test($(this).val())) {
                    document.getElementById('city_err').innerHTML = "Invalid City";
                    $("#city_err" ).show();
                    submit = false;
                }
            }
        });

        $("#id_city").focusin(function (event) {
            if (event.charCode!=0) {
                $("#city_err" ).hide();
                document.getElementById('city_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_pincode").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[0-9]{6}$");
                if (!regex.test($("#id_pincode").val())) {
                    document.getElementById('pincode_err').innerHTML = "Invalid Pincode";
                    $("#pincode_err").show();
                    submit = false;
                }
            }
        });

        $("#id_pincode").focusin(function (event) {
            if (event.charCode!=0) {
                $("#pincode_err").hide();
                document.getElementById('pincode_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_organisation").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[a-zA-Z ]+$");
                if (!regex.test($(this).val())) {
                    document.getElementById('org_err').innerHTML = "Invalid Organisation";
                    $("#org_err" ).show();
                    submit = false;
                }
            }
        });

        $("#id_organisation").focusin(function (event) {
            if (event.charCode!=0) {
                $("#org_err" ).hide();
                document.getElementById('org_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_designation").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[a-zA-Z ]+$");
                if (!regex.test($(this).val())) {
                    document.getElementById('des_err').innerHTML = "Invalid Designation";
                    $("#des_err" ).show();
                    submit = false;
                }
            }
        });

        $("#id_designation").focusin(function (event) {
            if (event.charCode!=0) {
                $("#des_err" ).hide();
                document.getElementById('des_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_captcha").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[0-9]+$");
                if (!regex.test($("#id_captcha").val())) {
                    document.getElementById('captcha_err').innerHTML = "Invalid Captcha";
                    $( "#captcha_err").show();
                    submit = false;
                }
            }
        });

        $("#id_captcha").focusin(function (event) {
            if (event.charCode!=0) {
                $( "#captcha_err" ).hide();
                document.getElementById('captcha_err').innerHTML = "";
                submit = true;
            }
        });

        $("#id_submit").click(function (e) {
             if(submit==false){
                e.preventDefault();
                console.log("working")
                $("#id_submit").css('cursor', 'not-allowed');
             }
             else{
                $("#id_submit").css('cursor', 'pointer');
             }
             });

        $("#id_submit").hover(function (e) {
             if(submit==false ||
                (document.getElementById('first_name_err').innerHTML == "") ||
                (document.getElementById('middle_name_err').innerHTML == "") ||
                (document.getElementById('last_name_err').innerHTML == "") ||
                (document.getElementById('address_err').innerHTML == "") ||
                (document.getElementById('city_err').innerHTML == "") ||
                (document.getElementById('pincode_err').innerHTML == "") ||
                (document.getElementById('org_err').innerHTML == "") ||
                (document.getElementById('des_err').innerHTML == "") ||
                (document.getElementById('captcha_err').innerHTML == "")
){
                e.preventDefault();
                console.log("working")
                $("#id_submit").css('cursor', 'not-allowed');
             }
             else{
                $("#id_submit").css('cursor', 'pointer');
             }
             });

    });

</script>

</body>
</html>
{% endblock %}